=== ZMYaro/kanjiz/lists/kanjiList.dtd
<!DOCTYPE app [
	<!ELEMENT kanjiList (name, listItem)>
	
	<!ELEMENT name (#PCDATA)>     <!-- the name of the kanji list    -->
	
	<!ELEMENT listItem (kanji,hiragana,english)> <!-- an item in the kanjiList -->
	<!ELEMENT kanji    (#PCDATA)> <!-- the kanji for the listItem    -->
	<!ELEMENT kana (#PCDATA)> <!-- the hiragana for the listItem -->
	<!ELEMENT english  (#PCDATA)> <!-- the English translation of the listItem -->
]>

=== ZMYaro/kanjiz/app/lists/bk1_ch1_l4.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE kanjiList SYSTEM "kanjiList.dtd">
<kanjiList>
	<name>Chapter 1, Lesson 4, Vocabulary</name>
	<listItem>
		<kanji>始める</kanji>
		<kana>はじめる</kana>
		<english>begin</english>
	</listItem>
	<listItem>
		<kanji>始めましょう</kanji>
		<kana>はじめましょう</kana>
		<english>let us begin</english>
	</listItem>
	<listItem>
		<kanji>規律。</kanji>
		<kana>きりつ。</kana>
		<english>Stand. (command used at ceremonies or in formal situations)</english>
	</listItem>
	<listItem>
		<kanji>れい。</kanji>
		<kana>れい。</kana>
		<english>Bow. (command used at ceremonies or in formal situations)</english>
	</listItem>
	<listItem>
		<kanji>着席。</kanji>
		<kana>ちゃくせき。</kana>
		<english>Sit. (command used at ceremonies or in formal situations)</english>
	</listItem>
	<listItem>
		<kanji>（お）休みです</kanji>
		<kana>（お）やすみです</kana>
		<english>is absent</english>
	</listItem>
	<listItem>
		<kanji>遅刻です</kanji>
		<kana>ちこくです</kana>
		<english>is tardy</english>
	</listItem>
	<listItem>
		<kanji>速く</kanji>
		<kana>はやく</kana>
		<english>hurry!</english>
	</listItem>
	<listItem>
		<kanji>終わる</kanji>
		<kana>おわる</kana>
		<english>finish</english>
	</listItem>
	<listItem>
		<kanji>終わりましょう</kanji>
		<kana>おわりましょう</kana>
		<english>let's finish</english>
	</listItem>
	<listItem>
		<kanji>何</kanji>
		<kana>なに/なん</kana>
		<english>what</english>
	</listItem>
	<listItem>
		<kanji>～か</kanji>
		<kana>～か</kana>
		<english>[particle indicating a question]</english>
	</listItem>
	<listItem>
		<kanji>住みません。遅く　なりました。</kanji>
		<kana>すみません。おそく　なりました。</kana>
		<english>I am sorry to be late.</english>
	</listItem>
</kanjiList>

=== ZMYaro/kanjiz/app/lists/aij2_ch10_l1.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE kanjiList SYSTEM "kanjiList.dtd">
<kanjiList>
	<name>Book 2, Chapter 10, Lesson 1 Vocabulary</name>
	<listItem>
		<kanji>時間</kanji>
		<kana>じかん</kana>
		<english>time</english>
	</listItem>
	<listItem>
		<kanji>場所</kanji>
		<kana>ばしょ</kana>
		<english>location, place</english>
	</listItem>
	<listItem>
		<kanji>体育館</kanji>
		<kana>たいいくかん</kana>
		<english>gym</english>
	</listItem>
	<listItem>
		<kanji>運動場</kanji>
		<kana>うんどうじょう</kana>
		<english>athletic field</english>
	</listItem>
	<listItem>
		<kanji>運動</kanji>
		<kana>うんどう</kana>
		<english>sports</english>
	</listItem>
	<listItem>
		<kanji>ユニフォーム</kanji>
		<kana>ユニフォーム</kana>
		<english>uniform</english>
	</listItem>
	<listItem>
		<kanji>選手</kanji>
		<kana>せんしゅ</kana>
		<english>[sports] player</english>
	</listItem>
	<listItem>
		<kanji>試合に 出る</kanji>
		<kana>しあいに でる</kana>
		<english>to participate in a [sports] game</english>
	</listItem>
	<listItem>
		<kanji>応援 (を) する</kanji>
		<kana>おうえん (を) する</kana>
		<english>to cheer</english>
	</listItem>
	<listItem>
		<kanji>〜が 始まる</kanji>
		<kana>〜が はじまる</kana>
		<english>~ begins, starts</english>
	</listItem>
	<listItem>
		<kanji>〜が 終わる</kanji>
		<kana>〜が おわる</kana>
		<english>~ finishes, ends</english>
	</listItem>
	<listItem>
		<kanji>陸上</kanji>
		<kana>りくじょう</kana>
		<english>track</english>
	</listItem>
	<listItem>
		<kanji>チヤーリーダー</kanji>
		<kana>チヤーリーダー</kana>
		<english>cheerleader</english>
	</listItem>
	<listItem>
		<kanji>プロ</kanji>
		<kana>プロ</kana>
		<english>professional</english>
	</listItem>
	<listItem>
		<kanji>アマ(チア)</kanji>
		<kana>アマ(チア)</kana>
		<english>amateur</english>
	</listItem>
	<listItem>
		<kanji>スタジアム</kanji>
		<kana>スタジアム</kana>
		<english>stadium</english>
	</listItem>
	<listItem>
		<kanji>ドーム</kanji>
		<kana>ドーム</kana>
		<english>dorm</english>
	</listItem>
	<listItem>
		<kanji>きょうぎじょう</kanji>
		<kana>きょうぎじょう</kana>
		<english>track field</english>
	</listItem>
	<listItem>
		<kanji>トーナメント</kanji>
		<kana>トーナメント</kana>
		<english>tournament</english>
	</listItem>
</kanjiList>

=== ZMYaro/kanjiz/app/lists/aij2_ch09_l4.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE kanjiList SYSTEM "kanjiList.dtd">
<kanjiList>
	<name>Book 2, Chapter 9, Lesson 4 Vocabulary</name>
	<listItem>
		<kanji>(お)みやげ</kanji>
		<kana>(お)みやげ</kana>
		<english>souvenir gift</english>
	</listItem>
	<listItem>
		<kanji>はこ</kanji>
		<kana>はこ</kana>
		<english>box</english>
	</listItem>
	<listItem>
		<kanji>ふくる</kanji>
		<kana>ふくる</kana>
		<english>paper bag</english>
	</listItem>
	<listItem>
		<kanji>〜に 入れる</kanji>
		<kana>〜に いれる</kana>
		<english>put in ~</english>
	</listItem>
	<listItem>
		<kanji>〜に 入れます</kanji>
		<kana>〜に いれます</kana>
		<english>to put in ~</english>
	</listItem>
	<listItem>
		<kanji>税金</kanji>
		<kana>ぜいきん</kana>
		<english>tax</english>
	</listItem>
	<listItem>
		<kanji>おつり</kanji>
		<kana>おつり</kana>
		<english>change [from a larger unit of money]</english>
	</listItem>
	<listItem>
		<kanji>トラベラーズ チェック</kanji>
		<kana>トラベラーズ チェック</kana>
		<english>traveler's check</english>
	</listItem>
	<listItem>
		<kanji>クレジット カード</kanji>
		<kana>クレジット カード</kana>
		<english>credit card</english>
	</listItem>
	<listItem>
		<kanji>地下</kanji>
		<kana>ちか</kana>
		<english>basement</english>
	</listItem>
	<listItem>
		<kanji>かかる</kanji>
		<kana>かかる</kana>
		<english>require [tax]; take [time]</english>
	</listItem>
	<listItem>
		<kanji>かかります</kanji>
		<kana>かかります</kana>
		<english>to require [tax]; to take [time]</english>
	</listItem>
	<listItem>
		<kanji>売って います</kanji>
		<kana>うって います</kana>
		<english>are selling</english>
	</listItem>
	<listItem>
		<kanji>また どうぞ。</kanji>
		<kana>また どうぞ。</kana>
		<english>Please come again.</english>
	</listItem>
	<listItem>
		<kanji>#かい</kanji>
		<kana>#かい</kana>
		<english>[#] floor</english>
	</listItem>
	<listItem>
		<kanji>ちか#かい</kanji>
		<kana>ちか#かい</kana>
		<english>basement [#] floor</english>
	</listItem>
	<listItem>
		<kanji>レシート</kanji>
		<kana>レシート</kana>
		<english>receipt</english>
	</listItem>
	<listItem>
		<kanji>しょうひぜい</kanji>
		<kana>しょうひぜい</kana>
		<english>sales tax</english>
	</listItem>
	<listItem>
		<kanji>現金</kanji>
		<kana>げんきん</kana>
		<english>cash</english>
	</listItem>
	<listItem>
		<kanji>小切手</kanji>
		<kana>こぎって</kana>
		<english>a check</english>
	</listItem>
</kanjiList>

=== ZMYaro/kanjiz/app/lists/aij2_ch14_l1.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE kanjiList SYSTEM "kanjiList.dtd">
<kanjiList>
	<name>Book 2, Chapter 14, Lesson 1 Vocabulary</name>
	<listItem>
		<kanji>作り方</kanji>
		<kana>つくりかた</kana>
		<english>how to make</english>
	</listItem>
	<listItem>
		<kanji>すき焼き</kanji>
		<kana>すきやき</kana>
		<english>&lt;i&gt;sukiyaki&lt;/i&gt;</english>
	</listItem>
	<listItem>
		<kanji>牛肉</kanji>
		<kana>ぎゅうにく</kana>
		<english>beef</english>
	</listItem>
	<listItem>
		<kanji>豚肉</kanji>
		<kana>ぶたにく</kana>
		<english>pork</english>
	</listItem>
	<listItem>
		<kanji>鳥肉</kanji>
		<kana>とりにく</kana>
		<english>chicken (meat)</english>
	</listItem>
	<listItem>
		<kanji>卵</kanji>
		<kana>たまご</kana>
		<english>egg</english>
	</listItem>
	<listItem>
		<kanji>野菜</kanji>
		<kana>やさい</kana>
		<english>vegetable</english>
	</listItem>
	<listItem>
		<kanji>果物</kanji>
		<kana>くだもの</kana>
		<english>fruit</english>
	</listItem>
	<listItem>
		<kanji>苺</kanji>
		<kana>いちご</kana>
		<english>strawberry</english>
	</listItem>
	<listItem>
		<kanji>糸こんにゃく</kanji>
		<kana>いとこんにゃく</kana>
		<english>shredded &lt;i&gt;konnyaku&lt;/i&gt;</english>
	</listItem>
	<listItem>
		<kanji>台所</kanji>
		<kana>だいどころ</kana>
		<english>kitchen</english>
	</listItem>
	<listItem>
		<kanji>材料</kanji>
		<kana>ざいりょう</kana>
		<english>ingredients</english>
	</listItem>
	<listItem>
		<kanji>カップ</kanji>
		<kana>カップ</kana>
		<english>cup (measurement)</english>
	</listItem>
	<listItem>
		<kanji>大サジ</kanji>
		<kana>おおサジ</kana>
		<english>tablespoon</english>
	</listItem>
	<listItem>
		<kanji>小サジ</kanji>
		<kana>こサジ</kana>
		<english>teaspoon</english>
	</listItem>
	<listItem>
		<kanji>二分の一</kanji>
		<kana>にぶんのいち</kana>
		<english>one half (1/2)</english>
	</listItem>
	<listItem>
		<kanji>トマト</kanji>
		<kana>トマト</kana>
		<english>tomato</english>
	</listItem>
	<listItem>
		<kanji>じゃがいも</kanji>
		<kana>じゃがいも</kana>
		<english>potato</english>
	</listItem>
	<listItem>
		<kanji>にんじん</kanji>
		<kana>にんじん</kana>
		<english>carrots</english>
	</listItem>
	<listItem>
		<kanji>たまねぎ</kanji>
		<kana>たまねぎ</kana>
		<english>round onion</english>
	</listItem>
	<listItem>
		<kanji>きゅうり</kanji>
		<kana>きゅうり</kana>
		<english>cucumber</english>
	</listItem>
	<listItem>
		<kanji>なす</kanji>
		<kana>なす</kana>
		<english>eggplant</english>
	</listItem>
	<listItem>
		<kanji>キャベツ</kanji>
		<kana>キャベツ</kana>
		<english>cabbage</english>
	</listItem>
	<listItem>
		<kanji>レタス</kanji>
		<kana>レタス</kana>
		<english>lettuce</english>
	</listItem>
	<listItem>
		<kanji>セロリ</kanji>
		<kana>セロリ</kana>
		<english>celery</english>
	</listItem>
	<listItem>
		<kanji>ピーマン</kanji>
		<kana>ピーマン</kana>
		<english>green pepper</english>
	</listItem>
	<listItem>
		<kanji>はす</kanji>
		<kana>はす</kana>
		<english>lotus root</english>
	</listItem>
	<listItem>
		<kanji>ねぎ</kanji>
		<kana>ねぎ</kana>
		<english>green onion</english>
	</listItem>
	<listItem>
		<kanji>ほうれんそう</kanji>
		<kana>ほうれんそう</kana>
		<english>spinich</english>
	</listItem>
	<listItem>
		<kanji>まめ</kanji>
		<kana>まめ</kana>
		<english>peas; beans</english>
	</listItem>
	<listItem>
		<kanji>だいこん</kanji>
		<kana>だいこん</kana>
		<english>turnip</english>
	</listItem>
	<listItem>
		<kanji>ごぼう</kanji>
		<kana>ごぼう</kana>
		<english>burdock</english>
	</listItem>
	<listItem>
		<kanji>りんご</kanji>
		<kana>りんご</kana>
		<english>apple</english>
	</listItem>
	<listItem>
		<kanji>オレンジ</kanji>
		<kana>オレンジ</kana>
		<english>orange</english>
	</listItem>
	<listItem>
		<kanji>グレープフルーツ</kanji>
		<kana>グレープフルーツ</kana>
		<english>grapefruit</english>
	</listItem>
	<listItem>
		<kanji>みかん</kanji>
		<kana>みかん</kana>
		<english>tangerine</english>
	</listItem>
	<listItem>
		<kanji>（よう）なし</kanji>
		<kana>（よう）なし</kana>
		<english>(Western) pear</english>
	</listItem>
	<listItem>
		<kanji>さくらんぼ</kanji>
		<kana>さくらんぼ</kana>
		<english>cherry</english>
	</listItem>
	<listItem>
		<kanji>すいか</kanji>
		<kana>すいか</kana>
		<english>watermelon</english>
	</listItem>
	<listItem>
		<kanji>バナナ</kanji>
		<kana>バナナ</kana>
		<english>banana</english>
	</listItem>
	<listItem>
		<kanji>パイナップル</kanji>
		<kana>パイナップル</kana>
		<english>pineapple</english>
	</listItem>
	<listItem>
		<kanji>桃</kanji>
		<kana>もも</kana>
		<english>peach</english>
	</listItem>
	<listItem>
		<kanji>ぶどう</kanji>
		<kana>ぶどう</kana>
		<english>grapes</english>
	</listItem>
	<listItem>
		<kanji>メロン</kanji>
		<kana>メロン</kana>
		<english>melon</english>
	</listItem>
	<listItem>
		<kanji>かき</kanji>
		<kana>かき</kana>
		<english>persimmon</english>
	</listItem>
</kanjiList>

=== ZMYaro/kanjiz/app/lists/aij1_ch15.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE kanjiList SYSTEM "kanjiList.dtd">
<kanjiList>
	<name>Book 1, Chapter 15 Vocabulary</name>
	
	<listItem>
		<kanji>遊ぶ</kanji>
		<kana>あそぶ</kana>
		<english>to play</english>
	</listItem>
	<listItem>
		<kanji>住所</kanji>
		<kana>じゅうしょ</kana>
		<english>address</english>
	</listItem>
	<listItem>
		<kanji>勉強</kanji>
		<kana>べんきょう</kana>
		<english>to study</english>
	</listItem>
	<listItem>
		<kanji>新聞</kanji>
		<kana>しんぶん</kana>
		<english>newspaper</english>
	</listItem>
	<listItem>
		<kanji>図書館</kanji>
		<kana>としょかん</kana>
		<english>library</english>
	</listItem>
	<listItem>
		<kanji>差し上げます</kanji>
		<kana>さしあげます</kana>
		<english>to give [to someone of higher status]</english>
	</listItem>
	<!-- not in book -->
	<listItem>
		<kanji>いただきます</kanji>
		<kana>いただきます</kana>
		<english>to receive [from someone of higher status]</english>
	</listItem>
	<listItem>
		<kanji>歌う</kanji>
		<kana>うたう</kana>
		<english>to sing</english>
	</listItem>
	<listItem>
		<kanji>友達</kanji>
		<kana>ともだち</kana>
		<english>friend</english>
	</listItem>
	<listItem>
		<kanji>誰</kanji>
		<kana>だれ</kana>
		<english>who</english>
	</listItem>
	<listItem>
		<kanji>作る</kanji>
		<kana>つくる</kana>
		<english>make</english>
	</listItem>
	<listItem>
		<kanji>泳ぐ</kanji>
		<kana>およぐ</kana>
		<english>to swim</english>
	</listItem>
	<listItem>
		<kanji>写真</kanji>
		<kana>しゃしん</kana>
		<english>picture</english>
	</listItem>
	<listItem>
		<kanji>毎年</kanji>
		<kana>まいとし</kana>
		<english>every year</english>
	</listItem>
	<listItem>
		<kanji>来年</kanji>
		<kana>らいねん</kana>
		<english>next year</english>
	</listItem>
	<listItem>
		<kanji>今年</kanji>
		<kana>ことし</kana>
		<english>this year</english>
	</listItem>
	<listItem>
		<kanji>去年</kanji>
		<kana>きょねん</kana>
		<english>last year</english>
	</listItem>
	<listItem>
		<kanji>番号</kanji>
		<kana>ばんごう</kana>
		<english>number</english>
	</listItem>
	<listItem>
		<kanji>電話</kanji>
		<kana>でんわ</kana>
		<english>telephone</english>
	</listItem>
	<listItem>
		<kanji>楽しみ</kanji>
		<kana>たのしみ</kana>
		<english>looking forward to</english>
	</listItem>
	<listItem>
		<kanji>(~を)楽しみに しています</kanji>
		<kana>(~を)たのしみに しています</kana>
		<english>looking forward to ~</english>
	</listItem>
	<listItem>
		<kanji>時</kanji>
		<kana>とき</kana>
		<english>when</english>
	</listItem>
	<listItem>
		<kanji>今月</kanji>
		<kana>こんげつ</kana>
		<english>this month</english>
	</listItem>
	<listItem>
		<kanji>今朝</kanji>
		<kana>けさ</kana>
		<english>this morning</english>
	</listItem>
	<listItem>
		<kanji>家</kanji>
		<kana>うち/いえ</kana>
		<english>house</english>
	</listItem>
	<listItem>
		<kanji>夕べ</kanji>
		<kana>ゆうべ</kana>
		<english>evening</english>
	</listItem>
	<listItem>
		<kanji>東京</kanji>
		<kana>とうきょう</kana>
		<english>Tokyo</english>
	</listItem>
	<listItem>
		<kanji>先月</kanji>
		<kana>せんげつ</kana>
		<english>last month</english>
	</listItem>
	<listItem>
		<kanji>妹</kanji>
		<kana>いもうと</kana>
		<english>younger sister</english>
	</listItem>
	<listItem>
		<kanji>読む</kanji>
		<kana>よむ</kana>
		<english>to read</english>
	</listItem>
	<listItem>
		<kanji>毎日</kanji>
		<kana>まいにち</kana>
		<english>every day</english>
	</listItem>
	<listItem>
		<kanji>花</kanji>
		<kana>はな</kana>
		<english>flower</english>
	</listItem>
	<listItem>
		<kanji>何</kanji>
		<kana>なに</kana>
		<english>what</english>
	</listItem>
	<listItem>
		<kanji>風船</kanji>
		<kana>ふうせん</kana>
		<english>balloon</english>
	</listItem>
</kanjiList>

=== ZMYaro/kanjiz/lists/bk2_ch2_l1.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE kanjiList SYSTEM "kanjiList.dtd">
<kanjiList>
	<name>Book 2, Chapter 2, Lesson 1 Vocabulary</name>
	
	<listItem>
		<kanji>生まれました</kanji>
		<kana>うまれました</kana>
		<english>was born</english>
	</listItem>
	<listItem>
		<kanji>生まれる</kanji>
		<kana>うまれる</kana>
		<english>to be born</english>
	</listItem>
	<listItem>
		<kanji>住んで　います</kanji>
		<kana>すんで　います</kana>
		<english>to live/reside (in)</english>
	</listItem>
	<listItem>
		<kanji>住む</kanji>
		<kana>すむ</kana>
		<english>to live/reside (in)</english>
	</listItem>
	<listItem>
		<kanji>(〜に) 勤めて　います</kanji>
		<kana>(〜に) つとめて　います</kana>
		<english>is employed (at ~)</english>
	</listItem>
	<listItem>
		<kanji>(〜で) 働いて　います</kanji>
		<kana>(〜で) はたらいて　います</kana>
		<english>is working (at ~)</english>
	</listItem>
	<listItem>
		<kanji>働く</kanji>
		<kana>はたらく</kana>
		<english>to work (at)</english>
	</listItem>
	<listItem>
		<kanji>働きます</kanji>
		<kana>はたらきます</kana>
		<english>to work (at)</english>
	</listItem>
	<listItem>
		<kanji>(〜で)（アル）バイト（を）して　います</kanji>
		<kana>(〜で)（アル）バイト（を）して　います</kana>
		<english>is working part time (at ~)</english>
	</listItem>
	<listItem>
		<kanji>（～と）結婚（を）して　います</kanji>
		<kana>（～と）けっこん（を）して　います</kana>
		<english>is married (to ~)</english>
	</listItem>
	<listItem>
		<kanji>持って　います</kanji>
		<kana>もって　います</kana>
		<english>have/posess/hold/carry</english>
	</listItem>
	<listItem>
		<kanji>知って　います</kanji>
		<kana>しって　います</kana>
		<english>(to) know</english>
	</listItem>
	<listItem>
		<kanji>知りません</kanji>
		<kana>しりません</kana>
		<english>do not know</english>
	</listItem>
	<listItem>
		<kanji>知ります</kanji>
		<kana>しります</kana>
		<english>to get to know</english>
	</listItem>
	<listItem>
		<kanji>習って　います</kanji>
		<kana>ならって　います</kana>
		<english>is learning</english>
	</listItem>
	<listItem>
		<kanji></kanji>
		<kana>ホームステイを　します</kana>
		<english>will do a homestay</english>
	</listItem>
</kanjiList>

=== ZMYaro/kanjiz/app/lists/genki2_l16_vocab.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE kanjiList SYSTEM "kanjiList.dtd">
<kanjiList>
	<name>Genki 2, Lesson 16 Vocabulary</name>
	<listItem>
		<kanji>駅員</kanji>
		<kana>えきいん</kana>
		<english>station attendant</english>
	</listItem>
	<listItem>
		<kanji>大きさ</kanji>
		<kana>おおきさ</kana>
		<english>size</english>
	</listItem>
	<listItem>
		<kanji>親</kanji>
		<kana>おや</kana>
		<english>parent</english>
	</listItem>
	<listItem>
		<kanji>期末試験</kanji>
		<kana>きまつしけん</kana>
		<english>final examination</english>
	</listItem>
	<listItem>
		<kanji>研究</kanji>
		<kana>けんきゅう</kana>
		<english>research</english>
	</listItem>
	<listItem>
		<kanji>ごみ</kanji>
		<kana>ごみ</kana>
		<english>garbage</english>
	</listItem>
	<listItem>
		<kanji>砂糖</kanji>
		<kana>さとう</kana>
		<english>sugar</english>
	</listItem>
	<listItem>
		<kanji>奨学金</kanji>
		<kana>しょうがくきん</kana>
		<english>scholarship</english>
	</listItem>
	<listItem>
		<kanji>親せき</kanji>
		<kana>しんせき</kana>
		<english>relatives</english>
	</listItem>
	<listItem>
		<kanji>推薦状</kanji>
		<kana>すいせんじょう</kana>
		<english>letter of recommendation</english>
	</listItem>
	<listItem>
		<kanji>大学院</kanji>
		<kana>だいがくいん</kana>
		<english>graduate school</english>
	</listItem>
	<listItem>
		<kanji>台風</kanji>
		<kana>たいふう</kana>
		<english>typhoon</english>
	</listItem>
	<listItem>
		<kanji>日</kanji>
		<kana>ひ</kana>
		<english>day</english>
	</listItem>
	<listItem>
		<kanji>ファイル</kanji>
		<kana>ファイル</kana>
		<english>file; portfolio</english>
	</listItem>
	<listItem>
		<kanji>道</kanji>
		<kana>みち</kana>
		<english>way; road; directions</english>
	</listItem>
	<listItem>
		<kanji>目覚まし時計</kanji>
		<kana>めざましどけい</kana>
		<english>alarm clock</english>
	</listItem>
	<listItem>
		<kanji>汚い</kanji>
		<kana>きたない</kana>
		<english>dirty</english>
	</listItem>
	<listItem>
		<kanji>（～を）起こす</kanji>
		<kana>（～を）おこす</kana>
		<english>to wake (someone) up</english>
	</listItem>
	<listItem>
		<kanji>（personにmealを）おごる</kanji>
		<kana>（personにmealを）おごる</kana>
		<english>to treat (person) to (meal)</english>
	</listItem>
	<listItem>
		<kanji>落ち込む</kanji>
		<kana>おちこむ</kana>
		<english>to get depressed</english>
	</listItem>
	<listItem>
		<kanji>困る</kanji>
		<kana>こまる</kana>
		<english>to have difficulty</english>
	</listItem>
	<listItem>
		<kanji>（～を）出す</kanji>
		<kana>（～を）だす</kana>
		<english>to take (something) out, to hand in (something)</english>
	</listItem>
	<listItem>
		<kanji>（personをplaceに）連れていく</kanji>
		<kana>（personをplaceに）つれていく</kana>
		<english>to take (someone) to (place)</english>
	</listItem>
	<listItem>
		<kanji>（～を）直す</kanji>
		<kana>（～を）なおす</kana>
		<english>to correct (~); to fix (~)</english>
	</listItem>
	<listItem>
		<kanji>道に迷う</kanji>
		<kana>みちにまよう</kana>
		<english>to become lost</english>
	</listItem>
	<listItem>
		<kanji>（～が）見つかる</kanji>
		<kana>（～が）みつかる</kana>
		<english>to be found</english>
	</listItem>
	<listItem>
		<kanji>（placeまで/にpersonを）迎えに行く</kanji>
		<kana>（placeまで/にpersonを）むかえに行く</kana>
		<english>to go pick up (person) from (place)</english>
	</listItem>
	<listItem>
		<kanji>（sourceをtargetに）訳す</kanji>
		<kana>（sourceをtargetに）やくす</kana>
		<english>to translate (source) into (target)</english>
	</listItem>
	<listItem>
		<kanji>笑う</kanji>
		<kana>わらう</kana>
		<english>to laugh</english>
	</listItem>
	<listItem>
		<kanji>（～に）アイロンをかける</kanji>
		<kana>（～に）アイロンをかける</kana>
		<english>to iron (clothes)</english>
	</listItem>
	<listItem>
		<kanji>（～を）集める</kanji>
		<kana>（～を）あつめる</kana>
		<english>to collect (~)</english>
	</listItem>
	<listItem>
		<kanji>（thingをplaceに）入れる</kanji>
		<kana>（thingをplaceに）いれる</kana>
		<english>to put (thing) in (place)</english>
	</listItem>
	<listItem>
		<kanji>（～に）乗り遅れる</kanji>
		<kana>（～に）のりおくれる</kana>
		<english>to miss (a train, bus, etc.)</english>
	</listItem>
	<listItem>
		<kanji>（～を）見せる</kanji>
		<kana>（～を）みせる</kana>
		<english>to show (~)</english>
	</listItem>
	<listItem>
		<kanji>朝寝坊する</kanji>
		<kana>あさねぼうする</kana>
		<english>to oversleep</english>
	</listItem>
	<listItem>
		<kanji>（placeを）案内する</kanji>
		<kana>（placeを）あんないする</kana>
		<english>to show [someone] around (place)</english>
	</listItem>
	<listItem>
		<kanji>説明する</kanji>
		<kana>せつめいする</kana>
		<english>to explain</english>
	</listItem>
	<listItem>
		<kanji>（placeまで/にpersonを）迎えに来る</kanji>
		<kana>（placeまで/にpersonを）むかえに来る</kana>
		<english>to go pick up (person) from (place)</english>
	</listItem>
	<listItem>
		<kanji>ええと</kanji>
		<kana>ええと</kana>
		<english>well...; let me see...</english>
	</listItem>
	<listItem>
		<kanji>今日中に</kanji>
		<kana>きょうじゅうに</kana>
		<english>by the end of today</english>
	</listItem>
	<listItem>
		<kanji>この間</kanji>
		<kana>このあいだ</kana>
		<english>the other day</english>
	</listItem>
	<listItem>
		<kanji>このぐらい</kanji>
		<kana>このぐらい</kana>
		<english>about this much</english>
	</listItem>
	<listItem>
		<kanji>ごめん</kanji>
		<kana>ごめん</kana>
		<english>I'm sorry (casual)</english>
	</listItem>
	<listItem>
		<kanji>これから</kanji>
		<kana>これから</kana>
		<english>from now on</english>
	</listItem>
	<listItem>
		<kanji>失礼します</kanji>
		<kana>しつれいします</kana>
		<english>excuse me; sorry to interrupt you</english>
	</listItem>
	<listItem>
		<kanji>自分で</kanji>
		<kana>じぶんで</kana>
		<english>(do something) by oneself</english>
	</listItem>
	<listItem>
		<kanji>授業中に</kanji>
		<kana>じゅぎょうちゅうに</kana>
		<english>in class; during the class</english>
	</listItem>
	<listItem>
		<kanji>ほかの</kanji>
		<kana>ほかの</kana>
		<english>other</english>
	</listItem>
</kanjiList>

=== ZMYaro/kanjiz/lists/cooking_ext.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE kanjiList SYSTEM "kanjiList.dtd">
<kanjiList>
	<name>Cooking extended vocabulary</name>
	<listItem>
		<kanji>みじん</kanji>
		<kana>みじん</kana>
		<english>in pieces</english>
	</listItem>
	<listItem>
		<kanji>みじんぎりにします</kanji>
		<kana>みじんぎりにします</kana>
		<english>to mince</english>
	</listItem>
	<listItem>
		<kanji>ねります</kanji>
		<kana>ねります</kana>
		<english>to mash/knead</english>
	</listItem>
	<listItem>
		<kanji>かけます</kanji>
		<kana>かけます</kana>
		<english>to pour</english>
	</listItem>
	<listItem>
		<kanji>フライがえし</kanji>
		<kana>フライがえし</kana>
		<english>spatula</english>
	</listItem>
	<listItem>
		<kanji>煮ます</kanji>
		<kana>にます</kana>
		<english>to simmer</english>
	</listItem>
</kanjiList>
