=== ZMYaro/kanjiz/lists/kanjiList.dtd
<!DOCTYPE app [
	<!ELEMENT kanjiList (name, listItem)>
	
	<!ELEMENT name (#PCDATA)>     <!-- the name of the kanji list    -->
	
	<!ELEMENT listItem (kanji,hiragana,english)> <!-- an item in the kanjiList -->
	<!ELEMENT kanji    (#PCDATA)> <!-- the kanji for the listItem    -->
	<!ELEMENT kana (#PCDATA)> <!-- the hiragana for the listItem -->
	<!ELEMENT english  (#PCDATA)> <!-- the English translation of the listItem -->
]>

=== ZMYaro/kanjiz/app/lists/aij1_ch05_l3.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE kanjiList SYSTEM "kanjiList.dtd">
<kanjiList>
	<name>Book 1, Chapter 5, Lesson 3 Vocabulary</name>
	<listItem>
		<kanji>上手</kanji>
		<kana>じょうず</kana>
		<english>skillful, be good at &lt;small&gt;referring to someone else&lt;/small&gt;</english>
	</listItem>
	<listItem>
		<kanji>下手</kanji>
		<kana>へた</kana>
		<english>unskillful, be poor at</english>
	</listItem>
	<listItem>
		<kanji>得意</kanji>
		<kana>とくい</kana>
		<english>be strong in, can do well</english>
	</listItem>
	<listItem>
		<kanji>苦手</kanji>
		<kana>にがて</kana>
		<english>be weak in</english>
	</listItem>
	<listItem>
		<kanji>事</kanji>
		<kana>こと</kana>
		<english>intangible thing</english>
	</listItem>
	<listItem>
		<kanji>フットボール</kanji>
		<kana>フットボール</kana>
		<english>football</english>
	</listItem>
	<listItem>
		<kanji>野球</kanji>
		<kana>やきゅう</kana>
		<english>baseball</english>
	</listItem>
	<listItem>
		<kanji>バスケット（ボール）</kanji>
		<kana>バスケット（ボール）</kana>
		<english>basketball</english>
	</listItem>
	<listItem>
		<kanji>バレー（ボール）</kanji>
		<kana>バレー（ボール）</kana>
		<english>volleyball</english>
	</listItem>
	<listItem>
		<kanji>サッカー</kanji>
		<kana>サッカー</kana>
		<english>soccer</english>
	</listItem>
	<listItem>
		<kanji>テニス</kanji>
		<kana>テニス</kana>
		<english>tennis</english>
	</listItem>
	<listItem>
		<kanji>ゴルフ</kanji>
		<kana>ゴルフ</kana>
		<english>golf</english>
	</listItem>
	<listItem>
		<kanji>Aが、B。</kanji>
		<kana>Aが、B。</kana>
		<english>A, but B.</english>
	</listItem>
	<listItem>
		<kanji>A。でも、B。</kanji>
		<kana>A。でも、B。</kana>
		<english>A.  But B.</english>
	</listItem>
	<listItem>
		<kanji>ボーリング</kanji>
		<kana>ボーリング</kana>
		<english>bowling</english>
	</listItem>
	<listItem>
		<kanji>スキー</kanji>
		<kana>スキー</kana>
		<english>skiing</english>
	</listItem>
	<listItem>
		<kanji>スケート</kanji>
		<kana>スケート</kana>
		<english>skating</english>
	</listItem>
	<listItem>
		<kanji>りくじょう</kanji>
		<kana>りくじょう</kana>
		<english>track</english>
	</listItem>
	<listItem>
		<kanji>きかいたいそう</kanji>
		<kana>きかいたいそう</kana>
		<english>gymnastics</english>
	</listItem>
</kanjiList>

=== ZMYaro/kanjiz/lists/bk2_ch7_l1.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE kanjiList SYSTEM "kanjiList.dtd">
<kanjiList>
	<name>Book 2, Chapter 7, Lesson 1 Vocabulary</name>
	
	<listItem>
		<kanji>クリスマス</kanji>
		<kana>クリスマス</kana>
		<english>Christmas</english>
	</listItem>
	<listItem>
		<kanji>クリスマスツリー</kanji>
		<kana>クリスマスツリー</kana>
		<english>Christmas tree</english>
	</listItem>
	<listItem>
		<kanji>クリスマスカード</kanji>
		<kana>クリスマスカード</kana>
		<english>Christmas card</english>
	</listItem>
	<listItem>
		<kanji>クリストきょう</kanji>
		<kana>クリストきょう</kana>
		<english>Christianity</english>
	</listItem>
	<listItem>
		<kanji>(お)正月</kanji>
		<kana>(お)しょうがつ</kana>
		<english>New Year</english>
	</listItem>
	<listItem>
		<kanji>(お)餅</kanji>
		<kana>(お)もち</kana>
		<english>pounded rice cakes</english>
	</listItem>
	<listItem>
		<kanji>着物</kanji>
		<kana>きもの</kana>
		<english>traditional Japanese wear</english>
	</listItem>
	<listItem>
		<kanji>年賀状</kanji>
		<kana>ねんがじょう</kana>
		<english>New Year's card</english>
	</listItem>
	<listItem>
		<kanji>お年玉</kanji>
		<kana>おとしだま</kana>
		<english>money received at New Year's</english>
	</listItem>
	<listItem>
		<kanji>教会</kanji>
		<kana>きょうきい</kana>
		<english>(Christian) church</english>
	</listItem>
	<listItem>
		<kanji>神社</kanji>
		<kana>じんじゃ</kana>
		<english>(Shinto) shrine</english>
	</listItem>
	<listItem>
		<kanji>(お)寺</kanji>
		<kana>(お)てら</kana>
		<english>(Buddhist) temple</english>
	</listItem>
	<listItem>
		<kanji>花火</kanji>
		<kana>はなび</kana>
		<english>fireworks</english>
	</listItem>
	<listItem>
		<kanji>花火(を します)</kanji>
		<kana>はなび(を します)</kana>
		<english>(to launch) fireworks</english>
	</listItem>
	<listItem>
		<kanji>送る</kanji>
		<kana>おくる</kana>
		<english>to send [mail]</english>
	</listItem>
	<listItem>
		<kanji>送ります</kanji>
		<kana>おくります</kana>
		<english>send [mail]</english>
	</listItem>
	<listItem>
		<kanji>初めて</kanji>
		<kana>はじめて</kana>
		<english>[for the] first time</english>
	</listItem>
	<listItem>
		<kanji>クリスマスイブ</kanji>
		<kana>クリスマスイブ</kana>
		<english>Christmas eve</english>
	</listItem>
	<listItem>
		<kanji>クリスマスケーキ</kanji>
		<kana>クリスマスケーキ</kana>
		<english>Christmas cake</english>
	</listItem>
	<listItem>
		<kanji>クリスマスプレゼント</kanji>
		<kana>クリスマスプレゼント</kana>
		<english>Christmas present</english>
	</listItem>
	<listItem>
		<kanji>サンタクロース</kanji>
		<kana>サンタクロース</kana>
		<english>Sänta Cläus</english>
	</listItem>
	<listItem>
		<kanji>晦日</kanji>
		<kana>みそか</kana>
		<english>December 30&lt;sup&gt;th&lt;/sup&gt;</english>
	</listItem>
	<listItem>
		<kanji>大晦日</kanji>
		<kana>おおみそか</kana>
		<english>New Year's Eve (December 31&lt;sup&gt;th&lt;/sup&gt;</english>
	</listItem>
	<listItem>
		<kanji>かざります</kanji>
		<kana>かざります</kana>
		<english>[to] decorate</english>
	</listItem>
	<listItem>
		<kanji>つつみます</kanji>
		<kana>つつみます</kana>
		<english>[to] wrap</english>
	</listItem>
	<listItem>
		<kanji>[verb た-form] ことが あります。</kanji>
		<kana>[verb た-form] ことが あります。</kana>
		<english>have done [verb]</english>
	</listItem>
</kanjiList>

=== ZMYaro/kanjiz/app/lists/aij2_ch06_l4.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE kanjiList SYSTEM "kanjiList.dtd">
<kanjiList>
	<name>Book 2, Chapter 6, Lesson 4 Vocabulary</name>
	
	<listItem>
		<kanji>一日に 三度</kanji>
		<kana>いちにちに さんど</kana>
		<english>three times per day</english>
	</listItem>
	<listItem>
		<kanji>〜も &lt;small&gt;(counter)&lt;/small&gt;</kanji>
		<kana>〜も &lt;small&gt;(counter)&lt;/small&gt;</kana>
		<english>as many/long as ~</english>
	</listItem>
	<listItem>
		<kanji>どのぐらい</kanji>
		<kana>どのぐらい</kana>
		<english>about how long/far/often?</english>
	</listItem>
	<listItem>
		<kanji>〜ど &lt;small&gt;(counter)&lt;/small&gt;</kanji>
		<kana>〜ど &lt;small&gt;(counter)&lt;/small&gt;</kana>
		<english>~ degree(s), time(s)</english>
	</listItem>
	<listItem>
		<kanji>〜分(間) &lt;small&gt;(counter)&lt;/small&gt;</kanji>
		<kana>〜ぶん(かん) &lt;small&gt;(counter)&lt;/small&gt;</kana>
		<english>~ minute(s)</english>
	</listItem>
	<listItem>
		<kanji>〜時間 &lt;small&gt;(counter)&lt;/small&gt;</kanji>
		<kana>〜じかん &lt;small&gt;(counter)&lt;/small&gt;</kana>
		<english>~ hour(s)</english>
	</listItem>
	<listItem>
		<kanji>〜日(間) &lt;small&gt;(counter)&lt;/small&gt;</kanji>
		<kana>〜日(かん) &lt;small&gt;(counter)&lt;/small&gt;</kana>
		<english>~ day(s)</english>
	</listItem>
	<listItem>
		<kanji>〜週間 &lt;small&gt;(counter)&lt;/small&gt;</kanji>
		<kana>〜しゅうかん &lt;small&gt;(counter)&lt;/small&gt;</kana>
		<english>~ week(s)</english>
	</listItem>
	<listItem>
		<kanji>〜か月 &lt;small&gt;(counter)&lt;/small&gt;</kanji>
		<kana>〜かげつ &lt;small&gt;(counter)&lt;/small&gt;</kana>
		<english>~ month(s)</english>
	</listItem>
	<listItem>
		<kanji>〜年(間) &lt;small&gt;(counter)&lt;/small&gt;</kanji>
		<kana>〜ねん(かん) &lt;small&gt;(counter)&lt;/small&gt;</kana>
		<english>~ year(s)</english>
	</listItem>
	<listItem>
		<kanji>〜秒 &lt;small&gt;(counter)&lt;/small&gt;</kanji>
		<kana>〜びょう &lt;small&gt;(counter)&lt;/small&gt;</kana>
		<english>~ second(s)</english>
	</listItem>
	<listItem>
		<kanji>世紀</kanji>
		<kana>せいき</kana>
		<english>century</english>
	</listItem>
</kanjiList>

=== ZMYaro/kanjiz/app/lists/bk2_ch6_l3.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE kanjiList SYSTEM "kanjiList.dtd">
<kanjiList>
	<name>Book 2, Chapter 6, Lesson 3 Vocabulary</name>
	
	<listItem>
		<kanji>行く つもりです</kanji>
		<kana>いく つもりです</kana>
		<english>plan to go</english>
	</listItem>
	<listItem>
		<kanji>行かない つもりです</kanji>
		<kana>いかない つもりです</kana>
		<english>do not plan to go</english>
	</listItem>
	<listItem>
		<kanji>行く はずです</kanji>
		<kana>いく はずです</kana>
		<english>I expect that he/she will go</english>
	</listItem>
	<listItem>
		<kanji>行かない はずです</kanji>
		<kana>いかない はずです</kana>
		<english>I expect that he/she will not go</english>
	</listItem>
	<listItem>
		<kanji>(クラスを) 取ります</kanji>
		<kana>(クラスを) とります</kana>
		<english>take (a class)</english>
	</listItem>
	<listItem>
		<kanji>(クラスを) 取る</kanji>
		<kana>(クラスを) とる</kana>
		<english>to take (a class)</english>
	</listItem>
	<listItem>
		<kanji>(運転免許を) 取る</kanji>
		<kana>(うんてんめんきょを) とる</kana>
		<english>to get (a driver's license)</english>
	</listItem>
	<listItem>
		<kanji>覚えます</kanji>
		<kana>おぼえます</kana>
		<english>memorize</english>
	</listItem>
	<listItem>
		<kanji>覚える</kanji>
		<kana>おぼえる</kana>
		<english>to memorize</english>
	</listItem>
	<listItem>
		<kanji>仕方が ありません。</kanji>
		<kana>しかたが ありません。</kana>
		<english>It cannot be helped.</english>
	</listItem>
	<listItem>
		<kanji>もちろん</kanji>
		<kana>もちろん</kana>
		<english>of course</english>
	</listItem>
	<listItem>
		<kanji>[reason]で</kanji>
		<kana>[reason]で</kana>
		<english>because of [reason]</english>
	</listItem>
	<listItem>
		<kanji>いじめ</kanji>
		<kana>いじめ</kana>
		<english>[the act of] bullying</english>
	</listItem>
</kanjiList>

=== ZMYaro/kanjiz/app/lists/genki2_l18_vocab.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE kanjiList SYSTEM "kanjiList.dtd">
<kanjiList>
	<name>Genki 2, Lesson 18 Vocabulary</name>
	<listItem>
		<kanji>あと</kanji>
		<kana>あと</kana>
		<english>the rest</english>
	</listItem>
	<listItem>
		<kanji>エアコン</kanji>
		<kana>エアコン</kana>
		<english>air conditioner</english>
	</listItem>
	<listItem>
		<kanji>カーテン</kanji>
		<kana>カーテン</kana>
		<english>curtain</english>
	</listItem>
	<listItem>
		<kanji>クッション</kanji>
		<kana>クッション</kana>
		<english>cushion</english>
	</listItem>
	<listItem>
		<kanji>シャンプー</kanji>
		<kana>シャンプー</kana>
		<english>shampoo</english>
	</listItem>
	<listItem>
		<kanji>醤油</kanji>
		<kana>しょうゆ</kana>
		<english>soy sauce</english>
	</listItem>
	<listItem>
		<kanji>スイッチ</kanji>
		<kana>スイッチ</kana>
		<english>switch</english>
	</listItem>
	<listItem>
		<kanji>スープ</kanji>
		<kana>スープ</kana>
		<english>soup</english>
	</listItem>
	<listItem>
		<kanji>スカート</kanji>
		<kana>スカート</kana>
		<english>skirt</english>
	</listItem>
	<listItem>
		<kanji>外</kanji>
		<kana>そと</kana>
		<english>outside</english>
	</listItem>
	<listItem>
		<kanji>ソファ</kanji>
		<kana>ソファ</kana>
		<english>sofa</english>
	</listItem>
	<listItem>
		<kanji>タオル</kanji>
		<kana>タオル</kana>
		<english>towel</english>
	</listItem>
	<listItem>
		<kanji>日記</kanji>
		<kana>にっき</kana>
		<english>diary</english>
	</listItem>
	<listItem>
		<kanji>バナナ</kanji>
		<kana>バナナ</kana>
		<english>banana</english>
	</listItem>
	<listItem>
		<kanji>ポップコーン</kanji>
		<kana>ポップコーン</kana>
		<english>popcorn</english>
	</listItem>
	<listItem>
		<kanji>虫</kanji>
		<kana>むし</kana>
		<english>insect</english>
	</listItem>
	<listItem>
		<kanji>家賃</kanji>
		<kana>やちん</kana>
		<english>rent</english>
	</listItem>
	<listItem>
		<kanji>夕方</kanji>
		<kana>ゆうがた</kana>
		<english>evening</english>
	</listItem>
	<listItem>
		<kanji>留守番電話</kanji>
		<kana>るすばんでんわ</kana>
		<english>answering machine</english>
	</listItem>
	<listItem>
		<kanji>冷蔵庫</kanji>
		<kana>れいぞうこ</kana>
		<english>refrigerator</english>
	</listItem>
	<listItem>
		<kanji>ろうそく</kanji>
		<kana>ろうそく</kana>
		<english>candle</english>
	</listItem>
	<listItem>
		<kanji>明るい</kanji>
		<kana>あかるい</kana>
		<english>bright</english>
	</listItem>
	<listItem>
		<kanji>気分が悪い</kanji>
		<kana>きぶんがわるい</kana>
		<english>to feel sick</english>
	</listItem>
	<listItem>
		<kanji>暗い</kanji>
		<kana>くらい</kana>
		<english>dark</english>
	</listItem>
	<listItem>
		<kanji>恥ずかしい</kanji>
		<kana>はずかしい</kana>
		<english>embarrassing; to feel embarrassed</english>
	</listItem>
	<listItem>
		<kanji>（～が）開く</kanji>
		<kana>（～が）あく</kana>
		<english>(something) opens</english>
	</listItem>
	<listItem>
		<kanji>（～に）謝る</kanji>
		<kana>（～に）あやまる</kana>
		<english>to apologize (to ~)</english>
	</listItem>
	<listItem>
		<kanji>（～を）押す</kanji>
		<kana>（～を）おす</kana>
		<english>to press; to push</english>
	</listItem>
	<listItem>
		<kanji>（～を）落とす</kanji>
		<kana>（～を）おとす</kana>
		<english>to drop (something)</english>
	</listItem>
	<listItem>
		<kanji>お湯が沸く</kanji>
		<kana>おゆがわく</kana>
		<english>water boils</english>
	</listItem>
	<listItem>
		<kanji>転ぶ</kanji>
		<kana>ころぶ</kana>
		<english>to fall down</english>
	</listItem>
	<listItem>
		<kanji>（～を）壊す</kanji>
		<kana>（～を）こわす</kana>
		<english>to break (something)</english>
	</listItem>
	<listItem>
		<kanji>（～が）咲く</kanji>
		<kana>（～が）さく</kana>
		<english>to bloom</english>
	</listItem>
	<listItem>
		<kanji>（～が）閉まる</kanji>
		<kana>（～が）しまる</kana>
		<english>(something) closes</english>
	</listItem>
	<listItem>
		<kanji>助かる</kanji>
		<kana>たすかる</kana>
		<english>to be saved; to be helped</english>
	</listItem>
	<listItem>
		<kanji>（personにfavorを）頼む</kanji>
		<kana>（personにfavorを）たのむ</kana>
		<english>to ask (a favor)</english>
	</listItem>
	<listItem>
		<kanji>（～が）つく</kanji>
		<kana>（～が）つく</kana>
		<english>(something) turns on</english>
	</listItem>
	<listItem>
		<kanji>（～を）汚す</kanji>
		<kana>（～を）よごす</kana>
		<english>to make (something) dirty</english>
	</listItem>
	<listItem>
		<kanji>（～が）落ちる</kanji>
		<kana>（～が）おちる</kana>
		<english>(something) drops</english>
	</listItem>
	<listItem>
		<kanji>（～を）片付ける</kanji>
		<kana>（～を）かたづける</kana>
		<english>to tidy up</english>
	</listItem>
	<listItem>
		<kanji>考える</kanji>
		<kana>かんがえる</kana>
		<english>to think (about); to consider</english>
	</listItem>
	<listItem>
		<kanji>（～が）消える</kanji>
		<kana>（～が）きえる</kana>
		<english>(something) goes off</english>
	</listItem>
	<listItem>
		<kanji>（～が）壊れる</kanji>
		<kana>（～が）こわれる</kana>
		<english>(something) breaks</english>
	</listItem>
	<listItem>
		<kanji>（～が）汚れる</kanji>
		<kana>（～が）よごれる</kana>
		<english>to become dirty</english>
	</listItem>
	<listItem>
		<kanji>（～を）注文する</kanji>
		<kana>（～を）ちゅうもんする</kana>
		<english>to place an order</english>
	</listItem>
	<listItem>
		<kanji>今すぐ</kanji>
		<kana>いますぐ</kana>
		<english>right away</english>
	</listItem>
	<listItem>
		<kanji>（～の）おかげで</kanji>
		<kana>（～の）おかげで</kana>
		<english>thanks to (~)</english>
	</listItem>
	<listItem>
		<kanji>お先に失礼します</kanji>
		<kana>おさきにしつれいします</kana>
		<english>See you. (lit., I'm leaving ahead of you.)</english>
	</listItem>
	<listItem>
		<kanji>お疲れ様（でした）</kanji>
		<kana>おつかれさま（でした）</kana>
		<english>You must be tired after working so hard.  (ritualistic expression)</english>
	</listItem>
	<listItem>
		<kanji>～（ん）だろう</kanji>
		<kana>～（ん）だろう</kana>
		<english>short form of ～（ん）でしょう</english>
	</listItem>
	<listItem>
		<kanji>どうしよう</kanji>
		<kana>どうしよう</kana>
		<english>What should I/we do?</english>
	</listItem>
	<listItem>
		<kanji>本当に</kanji>
		<kana>ほんとうに</kana>
		<english>really</english>
	</listItem>
	<listItem>
		<kanji>まず</kanji>
		<kana>まず</kana>
		<english>first of all</english>
	</listItem>
	<listItem>
		<kanji>（～）までに</kanji>
		<kana>（～）までに</kana>
		<english>by (time/date)</english>
	</listItem>
</kanjiList>

=== ZMYaro/kanjiz/app/lists/genki1_l10_kanji_ex.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE kanjiList SYSTEM "kanjiList.dtd">
<kanjiList>
	<name>Genki 1, Lesson 10 Kanji Examples</name>
	<listItem>
		<kanji>住む</kanji>
		<kana>すむ</kana>
		<english>to live</english>
	</listItem>
	<listItem>
		<kanji>住所</kanji>
		<kana>じゅうしょ</kana>
		<english>address</english>
	</listItem>
	<listItem>
		<kanji>移住する</kanji>
		<kana>いじゅうする</kana>
		<english>to immigrate</english>
	</listItem>
	<listItem>
		<kanji>お正月</kanji>
		<kana>おしょうがつ</kana>
		<english>New Year</english>
	</listItem>
	<listItem>
		<kanji>正しい</kanji>
		<kana>ただしい</kana>
		<english>right</english>
	</listItem>
	<listItem>
		<kanji>正午</kanji>
		<kana>しょうご</kana>
		<english>noon</english>
	</listItem>
	<listItem>
		<kanji>三年生</kanji>
		<kana>さんねんせい</kana>
		<english>third-year student</english>
	</listItem>
	<listItem>
		<kanji>来年</kanji>
		<kana>らいねん</kana>
		<english>next year</english>
	</listItem>
	<listItem>
		<kanji>今年</kanji>
		<kana>ことし</kana>
		<english>this year</english>
	</listItem>
	<listItem>
		<kanji>年</kanji>
		<kana>とし</kana>
		<english>year</english>
	</listItem>
	<listItem>
		<kanji>売る</kanji>
		<kana>うる</kana>
		<english>to sell</english>
	</listItem>
	<listItem>
		<kanji>売店</kanji>
		<kana>ばいてん</kana>
		<english>stand; stall</english>
	</listItem>
	<listItem>
		<kanji>自動販売機</kanji>
		<kana>じどうはんばいき</kana>
		<english>vending machine</english>
	</listItem>
	<listItem>
		<kanji>買う</kanji>
		<kana>かう</kana>
		<english>to buy</english>
	</listItem>
	<listItem>
		<kanji>買い物</kanji>
		<kana>かいもの</kana>
		<english>shopping</english>
	</listItem>
	<listItem>
		<kanji>売買</kanji>
		<kana>ばいばい</kana>
		<english>selling and buying</english>
	</listItem>
	<listItem>
		<kanji>町</kanji>
		<kana>まち</kana>
		<english>town</english>
	</listItem>
	<listItem>
		<kanji>北山町</kanji>
		<kana>きたやまちょう</kana>
		<english>Kitayama town</english>
	</listItem>
	<listItem>
		<kanji>町長</kanji>
		<kana>ちょうちょう</kana>
		<english>mayor of a town</english>
	</listItem>
	<listItem>
		<kanji>長い</kanji>
		<kana>ながい</kana>
		<english>long</english>
	</listItem>
	<listItem>
		<kanji>長男</kanji>
		<kana>ちょうなん</kana>
		<english>the eldest son</english>
	</listItem>
	<listItem>
		<kanji>社長</kanji>
		<kana>しゃちょう</kana>
		<english>company president</english>
	</listItem>
	<listItem>
		<kanji>道</kanji>
		<kana>みち</kana>
		<english>way; road</english>
	</listItem>
	<listItem>
		<kanji>書道</kanji>
		<kana>しょどう</kana>
		<english>calligraphy</english>
	</listItem>
	<listItem>
		<kanji>柔道</kanji>
		<kana>じゅうどう</kana>
		<english>judo</english>
	</listItem>
	<listItem>
		<kanji>北海道</kanji>
		<kana>ほっかいどう</kana>
		<english>Hokkaido</english>
	</listItem>
	<listItem>
		<kanji>雪</kanji>
		<kana>ゆき</kana>
		<english>snow</english>
	</listItem>
	<listItem>
		<kanji>新雪</kanji>
		<kana>しんせつ</kana>
		<english>new snow</english>
	</listItem>
	<listItem>
		<kanji>雪だるま</kanji>
		<kana>ゆきだるま</kana>
		<english>snowman</english>
	</listItem>
	<listItem>
		<kanji>立つ</kanji>
		<kana>たつ</kana>
		<english>to stand</english>
	</listItem>
	<listItem>
		<kanji>国立大学</kanji>
		<kana>こくりつだいがく</kana>
		<english>national university</english>
	</listItem>
	<listItem>
		<kanji>私立高校</kanji>
		<kana>しりつこうこう</kana>
		<english>private high school</english>
	</listItem>
	<listItem>
		<kanji>自分</kanji>
		<kana>じぶん</kana>
		<english>oneself</english>
	</listItem>
	<listItem>
		<kanji>自動車</kanji>
		<kana>じどうしゃ</kana>
		<english>automobile</english>
	</listItem>
	<listItem>
		<kanji>自転車</kanji>
		<kana>じてんしゃ</kana>
		<english>bicycle</english>
	</listItem>
	<listItem>
		<kanji>自由</kanji>
		<kana>じゆう</kana>
		<english>freedom</english>
	</listItem>
	<listItem>
		<kanji>夜</kanji>
		<kana>よる</kana>
		<english>night</english>
	</listItem>
	<listItem>
		<kanji>夜中</kanji>
		<kana>よなか</kana>
		<english>middle of night</english>
	</listItem>
	<listItem>
		<kanji>今夜</kanji>
		<kana>こんや</kana>
		<english>tonight</english>
	</listItem>
	<listItem>
		<kanji>夜明け</kanji>
		<kana>よあけ</kana>
		<english>dawn</english>
	</listItem>
	<listItem>
		<kanji>朝</kanji>
		<kana>あさ</kana>
		<english>morning</english>
	</listItem>
	<listItem>
		<kanji>今朝</kanji>
		<kana>けさ</kana>
		<english>this morning</english>
	</listItem>
	<listItem>
		<kanji>朝食</kanji>
		<kana>ちょうしょく</kana>
		<english>breakfast</english>
	</listItem>
	<listItem>
		<kanji>毎朝</kanji>
		<kana>まいあさ</kana>
		<english>every morning</english>
	</listItem>
	<listItem>
		<kanji>持つ</kanji>
		<kana>もつ</kana>
		<english>to hold</english>
	</listItem>
	<listItem>
		<kanji>持って来る</kanji>
		<kana>もってくる</kana>
		<english>to bring</english>
	</listItem>
	<listItem>
		<kanji>所持品</kanji>
		<kana>しょじひん</kana>
		<english>belongings</english>
	</listItem>
	<listItem>
		<kanji>気持ち</kanji>
		<kana>きもち</kana>
		<english>feeling</english>
	</listItem>
</kanjiList>

=== ZMYaro/kanjiz/app/lists/aij2_ch14_l2.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE kanjiList SYSTEM "kanjiList.dtd">
<kanjiList>
	<name>Book 2, Chapter 14, Lesson 2 Vocabulary</name>
	<listItem>
		<kanji></kanji>
		<kana>なべ</kana>
		<english>pot, pan</english>
	</listItem>
	<listItem>
		<kanji>油</kanji>
		<kana>あぶら</kana>
		<english>oil</english>
	</listItem>
	<listItem>
		<kanji></kanji>
		<kana>うすく</kana>
		<english>thin</english>
	</listItem>
	<listItem>
		<kanji></kanji>
		<kana>あつく</kana>
		<english>thick</english>
	</listItem>
	<listItem>
		<kanji>半分に</kanji>
		<kana>はんぶんに</kana>
		<english>in half</english>
	</listItem>
	<listItem>
		<kanji>切る/切ります</kanji>
		<kana>きる/きります</kana>
		<english>to cut; slice</english>
	</listItem>
	<listItem>
		<kanji>熱く　する</kanji>
		<kana>あつく　する</kana>
		<english>to make hot; to heat</english>
	</listItem>
	<listItem>
		<kanji></kanji>
		<kana>きれいに　する</kana>
		<english>to make clean; to clean</english>
	</listItem>
	<listItem>
		<kanji>まず</kanji>
		<kana>まず</kana>
		<english>first of all</english>
	</listItem>
	<listItem>
		<kanji>初めに</kanji>
		<kana>はじめに</kana>
		<english>at the beginning</english>
	</listItem>
	<listItem>
		<kanji>次に</kanji>
		<kana>つぎに</kana>
		<english>next</english>
	</listItem>
	<listItem>
		<kanji>終わりに</kanji>
		<kana>おわりに</kana>
		<english>at the end</english>
	</listItem>
	<listItem>
		<kanji>フライパン</kanji>
		<kana>フライパン</kana>
		<english>frying pan</english>
	</listItem>
	<listItem>
		<kanji>混ぜます</kanji>
		<kana>まぜます</kana>
		<english>to mix [transitive]</english>
	</listItem>
	<listItem>
		<kanji></kanji>
		<kana>おきます</kana>
		<english>to put; to place</english>
	</listItem>
	<listItem>
		<kanji></kanji>
		<kana>まきます</kana>
		<english>to roll</english>
	</listItem>
	<listItem>
		<kanji></kanji>
		<kana>おします</kana>
		<english>to push; to press</english>
	</listItem>
	<listItem>
		<kanji></kanji>
		<kana>ふっとうします</kana>
		<english>to boil</english>
	</listItem>
	<listItem>
		<kanji>その　あとで</kanji>
		<kana>その　あとで</kana>
		<english>after that</english>
	</listItem>
	<listItem>
		<kanji>その　間</kanji>
		<kana>その　あいだ</kana>
		<english>meanwhile</english>
	</listItem>
</kanjiList>

=== ZMYaro/kanjiz/lists/bk1_ch5_l5.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE kanjiList SYSTEM "kanjiList.dtd">
<kanjiList>
	<name>Book 1, Chapter 5, Lesson 5 Vocabulary</name>
	<listItem>
		<kanji>色</kanji>
		<kana>いろ</kana>
		<english>color</english>
	</listItem>
	<listItem>
		<kanji>何色</kanji>
		<kana>なにいろ</kana>
		<english>what color?</english>
	</listItem>
	<listItem>
		<kanji>赤</kanji>
		<kana>あか</kana>
		<english>red</english>
	</listItem>
	<listItem>
		<kanji>白</kanji>
		<kana>しろ</kana>
		<english>white</english>
	</listItem>
	<listItem>
		<kanji>黒</kanji>
		<kana>くろ</kana>
		<english>black</english>
	</listItem>
	<listItem>
		<kanji>青</kanji>
		<kana>あお</kana>
		<english>blue</english>
	</listItem>
	<listItem>
		<kanji>黄色</kanji>
		<kana>きいろ</kana>
		<english>yellow</english>
	</listItem>
	<listItem>
		<kanji>茶色</kanji>
		<kana>ちゃいろ</kana>
		<english>brown</english>
	</listItem>
	<listItem>
		<kanji>緑</kanji>
		<kana>みどり</kana>
		<english>green</english>
	</listItem>
	<listItem>
		<kanji>紫</kanji>
		<kana>むらさき</kana>
		<english>purple</english>
	</listItem>
	<listItem>
		<kanji>ピンク</kanji>
		<kana>ピンク</kana>
		<english>pink</english>
	</listItem>
	<listItem>
		<kanji>オレンジ（色）</kanji>
		<kana>オレンジ（いろ）</kana>
		<english>orange</english>
	</listItem>
	<listItem>
		<kanji>グレイ</kanji>
		<kana>グレイ</kana>
		<english>grey</english>
	</listItem>
	<listItem>
		<kanji>金色</kanji>
		<kana>きんいろ</kana>
		<english>gold (color)</english>
	</listItem>
	<listItem>
		<kanji>銀色</kanji>
		<kana>ぎんいろ</kana>
		<english>silver (color)</english>
	</listItem>
</kanjiList>
