=== ZMYaro/kanjiz/lists/kanjiList.dtd
<!DOCTYPE app [
	<!ELEMENT kanjiList (name, listItem)>
	
	<!ELEMENT name (#PCDATA)>     <!-- the name of the kanji list    -->
	
	<!ELEMENT listItem (kanji,hiragana,english)> <!-- an item in the kanjiList -->
	<!ELEMENT kanji    (#PCDATA)> <!-- the kanji for the listItem    -->
	<!ELEMENT kana (#PCDATA)> <!-- the hiragana for the listItem -->
	<!ELEMENT english  (#PCDATA)> <!-- the English translation of the listItem -->
]>

=== ZMYaro/kanjiz/lists/bk1_ch4_l4.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE kanjiList SYSTEM "kanjiList.dtd">
<kanjiList>
	<name>Book 1, Chapter 4, Lesson 4 Vocabulary</name>
	<listItem>
		<kanji>図書館</kanji>
		<kana>としょかん</kana>
		<english>library</english>
	</listItem>
	<listItem>
		<kanji>カフェテリア</kanji>
		<kana>カフェテリア</kana>
		<english>cafetaria</english>
	</listItem>
	<listItem>
		<kanji>スナック バー</kanji>
		<kana>スナック バー</kana>
		<english>snack bar</english>
	</listItem>
	<listItem>
		<kanji>[person]と</kanji>
		<kana>[person]と</kana>
		<english>with [person]</english>
	</listItem>
	<listItem>
		<kanji>いっしょに</kanji>
		<kana>いっしょに</kana>
		<english>together</english>
	</listItem>
	<listItem>
		<kanji>新聞</kanji>
		<kana>しんぶん</kana>
		<english>newspaper</english>
	</listItem>
	<listItem>
		<kanji>雑誌</kanji>
		<kana>ざっし</kana>
		<english>magazine</english>
	</listItem>
	<listItem>
		<kanji>ウォークマン</kanji>
		<kana>ウォークマン</kana>
		<english>walkman</english>
	</listItem>
	<listItem>
		<kanji>テープ</kanji>
		<kana>テープ</kana>
		<english>tape</english>
	</listItem>
	<listItem>
		<kanji>読みます/読む</kanji>
		<kana>よみます/よむ</kana>
		<english>to read</english>
	</listItem>
	<listItem>
		<kanji>聞きます/聞く</kanji>
		<kana>ききます/きく</kana>
		<english>to listen, hear</english>
	</listItem>
	<listItem>
		<kanji>します/する</kanji>
		<kana>します/する</kana>
		<english>to do</english>
	</listItem>
	<listItem>
		<kanji>勉強（を） します</kanji>
		<kana>べんきょう（を） します</kana>
		<english>to study</english>
	</listItem>
	<listItem>
		<kanji>シーディ</kanji>
		<kana>シーディ</kana>
		<english>CD</english>
	</listItem>
	<listItem>
		<kanji>シーディ プレーヤー</kanji>
		<kana>シーディ プレーヤー</kana>
		<english>CD player</english>
	</listItem>
	<listItem>
		<kanji>ランゲージ ラボ</kanji>
		<kana>ランゲージ ラボ</kana>
		<english>language lab</english>
	</listItem>
</kanjiList>

=== ZMYaro/kanjiz/lists/bk1_ch4_l5.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE kanjiList SYSTEM "kanjiList.dtd">
<kanjiList>
	<name>Book 1, Chapter 4, Lesson 5 Vocabulary</name>
	<listItem>
		<kanji>見ます/見る</kanji>
		<kana>みます/みる</kana>
		<english>to watch, look, see</english>
	</listItem>
	<listItem>
		<kanji>書きます/書く</kanji>
		<kana>かきます/かく</kana>
		<english>to write, draw</english>
	</listItem>
	<listItem>
		<kanji>タイプ（を） します</kanji>
		<kana>タイプ（を） します</kana>
		<english>to type</english>
	</listItem>
	<listItem>
		<kanji>テレビ</kanji>
		<kana>テレビ</kana>
		<english>television</english>
	</listItem>
	<listItem>
		<kanji>レポート</kanji>
		<kana>レポート</kana>
		<english>report</english>
	</listItem>
	<listItem>
		<kanji>手紙</kanji>
		<kana>てがみ</kana>
		<english>letter</english>
	</listItem>
	<listItem>
		<kanji>ラジオ</kanji>
		<kana>ラジオ</kana>
		<english>radio</english>
	</listItem>
	<listItem>
		<kanji>電話</kanji>
		<kana>でんわ</kana>
		<english>telephone</english>
	</listItem>
	<listItem>
		<kanji>コンピューター</kanji>
		<kana>コンピューター</kana>
		<english>computer</english>
	</listItem>
	<listItem>
		<kanji>ビデオ</kanji>
		<kana>ビデオ</kana>
		<english>video</english>
	</listItem>
	<listItem>
		<kanji>[tool]で</kanji>
		<kana>[tool]で</kana>
		<english>by/with/on [tool]</english>
	</listItem>
	<listItem>
		<kanji>ニュース</kanji>
		<kana>ニュース</kana>
		<english>news</english>
	</listItem>
	<listItem>
		<kanji>アニメ</kanji>
		<kana>アニメ</kana>
		<english>cartoons</english>
	</listItem>
	<listItem>
		<kanji>テレビ ゲーム</kanji>
		<kana>テレビ ゲーム</kana>
		<english>video game</english>
	</listItem>
	<listItem>
		<kanji>まんが</kanji>
		<kana>まんが</kana>
		<english>comics</english>
	</listItem>
</kanjiList>

=== ZMYaro/kanjiz/lists/bk2_ch1_l2.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE kanjiList SYSTEM "kanjiList.dtd">
<kanjiList>
	<name>Book 2, Chapter 1, Lesson 2 Vocabulary</name>
	<description>Geography of Japan</description>
	
	<listItem>
		<kanji>日本</kanji>
		<kana>にほん/にっぽん</kana>
		<english>Japan</english>
	</listItem>
	<listItem>
		<kanji>北</kanji>
		<kana>きた</kana>
		<english>north</english>
	</listItem>
	<listItem>
		<kanji>西</kanji>
		<kana>にし</kana>
		<english>west</english>
	</listItem>
	<listItem>
		<kanji>東</kanji>
		<kana>ひがし</kana>
		<english>east</english>
	</listItem>
	<listItem>
		<kanji>南</kanji>
		<kana>みなみ</kana>
		<english>south</english>
	</listItem>
	<listItem>
		<kanji>北海道</kanji>
		<kana>ほっかいどう</kana>
		<english>Hokkaido (island of Japan) &lt;img src="/kanjitest/hokkaido.gif" style="vertical-align:middle;"/&gt;</english>
	</listItem>
	<listItem>
		<kanji>本州</kanji>
		<kana>ほんしゅう</kana>
		<english>Honshu  (island of Japan) &lt;img src="/kanjitest/honshu.gif" style="vertical-align:middle;"/&gt;</english>
	</listItem>
	<listItem>
		<kanji>四国</kanji>
		<kana>しこく</kana>
		<english>Shikoku (island of Japan) &lt;img src="/kanjitest/shikoku.gif" style="vertical-align:middle;"/&gt;</english>
	</listItem>
	<listItem>
		<kanji>九州</kanji>
		<kana>きゅうしゅう</kana>
		<english>Kyushu (island of Japan) &lt;img src="/kanjitest/kyushu.gif" style="vertical-align:middle;"/&gt;</english>
	</listItem>
	<listItem>
		<kanji>沖縄</kanji>
		<kana>おきなわ</kana>
		<english>Okinawa (island of Japan)</english>
	</listItem>
	<listItem>
		<kanji>札幌</kanji>
		<kana>さっぽろ</kana>
		<english>Sapporo</english>
	</listItem>
	<listItem>
		<kanji>仙台</kanji>
		<kana>せんだい</kana>
		<english>Sendai</english>
	</listItem>
	<listItem>
		<kanji>東京</kanji>
		<kana>とうきょう</kana>
		<english>Tokyō</english>
	</listItem>
	<listItem>
		<kanji>名古屋</kanji>
		<kana>なごや</kana>
		<english>Nagoya</english>
	</listItem>
	<listItem>
		<kanji>京都</kanji>
		<kana>きょうと</kana>
		<english>Kyoto</english>
	</listItem>
	<listItem>
		<kanji>奈良</kanji>
		<kana>なら</kana>
		<english>Nara</english>
	</listItem>
	<listItem>
		<kanji>大阪</kanji>
		<kana>おおさか</kana>
		<english>osaka</english>
	</listItem>
	<listItem>
		<kanji>神戸</kanji>
		<kana>こうべ</kana>
		<english>Kobe</english>
	</listItem>
	<listItem>
		<kanji>広島</kanji>
		<kana>ひろしま</kana>
		<english>Hiroshima</english>
	</listItem>
	<listItem>
		<kanji>福岡</kanji>
		<kana>ふくおか</kana>
		<english>Fukuoka</english>
	</listItem>
	<listItem>
		<kanji>那覇</kanji>
		<kana>なは</kana>
		<english>Naha</english>
	</listItem>
</kanjiList>

=== ZMYaro/kanjiz/lists/clothes_ext.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE kanjiList SYSTEM "kanjiList.dtd">
<kanjiList>
	<name>Book 2, Chapter 3, Lesson 1 Additional Words</name>
	
	<listItem>
		<kanji>ストライプ(の～）</kanji>
		<kana>ストライプ(の～）</kana>
		<english>striped </english>
	</listItem>
	<listItem>
		<kanji>水玉（の～）</kanji>
		<kana>みずたま（の～）</kana>
		<english>polka dotted</english>
	</listItem>
	<listItem>
		<kanji>たて</kanji>
		<kana>たて</kana>
		<english>vertical</english>
	</listItem>
	<listItem>
		<kanji>よこ</kanji>
		<kana>よこ</kana>
		<english>side</english>
	</listItem>
	<listItem>
		<kanji>パーム</kanji>
		<kana>パーム</kana>
		<english>perm</english>
	</listItem>
	<listItem>
		<kanji>パームを　かけて　います</kanji>
		<kana>パームを　かけて　います</kana>
		<english>has a perm</english>
	</listItem>
</kanjiList>

=== ZMYaro/kanjiz/lists/bk2_ch9_l2.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE kanjiList SYSTEM "kanjiList.dtd">
<kanjiList>
	<name>Book 2, Chapter 9, Lesson 2 Vocabulary</name>
	<listItem>
		<kanji>〜ほど + [neg.]</kanji>
		<kana>〜ほど + [neg.]</kana>
		<english>[not] as ~ as</english>
	</listItem>
	<listItem>
		<kanji>(お)ねだん</kanji>
		<kana>(お)ねだん</kana>
		<english>price</english>
	</listItem>
	<listItem>
		<kanji>デザイン</kanji>
		<kana>デザイン</kana>
		<english>design</english>
	</listItem>
	<listItem>
		<kanji>セール(中)</kanji>
		<kana>セール(ちゅう)</kana>
		<english>on sale</english>
	</listItem>
	<listItem>
		<kanji>いろいろ</kanji>
		<kana>いろいろ</kana>
		<english>various</english>
	</listItem>
	<listItem>
		<kanji>ほか</kanji>
		<kana>ほか</kana>
		<english>other</english>
	</listItem>
	<listItem>
		<kanji>くらべる</kanji>
		<kana>くらべる</kana>
		<english>to compare</english>
	</listItem>
	<listItem>
		<kanji>同じ</kanji>
		<kana>おなじ</kana>
		<english>same</english>
	</listItem>
	<listItem>
		<kanji>ちがう</kanji>
		<kana>ちがう</kana>
		<english>is different/is wrong</english>
	</listItem>
</kanjiList>

=== ZMYaro/kanjiz/lists/bk2_ch9_kanjis.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE kanjiList SYSTEM "kanjiList.dtd">
<kanjiList>
	<name>Book 2, Chapter 9 Kanjis</name>
	<listItem>
		<kanji>両方</kanji>
		<kana>りょうほう</kana>
		<english>both</english>
	</listItem>
	<listItem>
		<kanji>店員</kanji>
		<kana>てんいん</kana>
		<english>store clerk</english>
	</listItem>
	<listItem>
		<kanji>同じ</kanji>
		<kana>おなじ</kana>
		<english>same</english>
	</listItem>
	<listItem>
		<kanji>世界</kanji>
		<kana>せかい</kana>
		<english>world</english>
	</listItem>
	<listItem>
		<kanji>国</kanji>
		<kana>くに</kana>
		<english>country, nation</english>
	</listItem>
	<listItem>
		<kanji>州</kanji>
		<kana>しゅう</kana>
		<english>state</english>
	</listItem>
	<listItem>
		<kanji>市</kanji>
		<kana>し</kana>
		<english>city</english>
	</listItem>
	<listItem>
		<kanji>島</kanji>
		<kana>しま</kana>
		<english>island</english>
	</listItem>
	<listItem>
		<kanji>町</kanji>
		<kana>まち</kana>
		<english>town</english>
	</listItem>
	<listItem>
		<kanji>村</kanji>
		<kana>むら</kana>
		<english>village</english>
	</listItem>
	<listItem>
		<kanji>〜に 入れる</kanji>
		<kana>〜に いれる</kana>
		<english>put in ~</english>
	</listItem>
	<listItem>
		<kanji>税金</kanji>
		<kana>ぜいきん</kana>
		<english>tax</english>
	</listItem>
	<listItem>
		<kanji>地下</kanji>
		<kana>ちか</kana>
		<english>basement</english>
	</listItem>
	<listItem>
		<kanji>現金</kanji>
		<kana>げんきん</kana>
		<english>cash</english>
	</listItem>
	<listItem>
		<kanji>小切手</kanji>
		<kana>こぎって</kana>
		<english>a check</english>
	</listItem>
</kanjiList>

=== ZMYaro/kanjiz/app/lists/bk2_ch7_l2_extra.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE kanjiList SYSTEM "kanjiList.dtd">
<kanjiList>
	<name>Book 2, Chapter 7, Lesson 2 Additional Words</name>
	<listItem>
		<kanji>最高気温</kanji>
		<kana>さいこう きおん</kana>
		<english>high temperature</english>
	</listItem>
	<listItem>
		<kanji>最低気温</kanji>
		<kana>さいてい きおん</kana>
		<english>lowest temperature</english>
	</listItem>
</kanjiList>

=== ZMYaro/kanjiz/app/lists/genki2_l13_vocab.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE kanjiList SYSTEM "kanjiList.dtd">
<kanjiList>
	<name>Genki 2, Lesson 13 Vocabulary</name>
	<listItem>
		<kanji>ウエイター</kanji>
		<kana>ウエイター</kana>
		<english>waiter</english>
	</listItem>
	<listItem>
		<kanji>お宅</kanji>
		<kana>おたく</kana>
		<english>(someone's) house/home</english>
	</listItem>
	<listItem>
		<kanji>大人</kanji>
		<kana>おとな</kana>
		<english>adult</english>
	</listItem>
	<listItem>
		<kanji>外国語</kanji>
		<kana>がいこくご</kana>
		<english>foreign language</english>
	</listItem>
	<listItem>
		<kanji>楽器</kanji>
		<kana>がっき</kana>
		<english>musical instrument</english>
	</listItem>
	<listItem>
		<kanji>空手</kanji>
		<kana>からて</kana>
		<english>karate</english>
	</listItem>
	<listItem>
		<kanji>カレー</kanji>
		<kana>カレー</kana>
		<english>curry</english>
	</listItem>
	<listItem>
		<kanji>着物</kanji>
		<kana>きもの</kana>
		<english>kimono; Japanese traditional dress</english>
	</listItem>
	<listItem>
		<kanji>広告</kanji>
		<kana>こうこく</kana>
		<english>advertisement</english>
	</listItem>
	<listItem>
		<kanji>紅茶</kanji>
		<kana>こうちゃ</kana>
		<english>black tea</english>
	</listItem>
	<listItem>
		<kanji>言葉</kanji>
		<kana>ことば</kana>
		<english>language</english>
	</listItem>
	<listItem>
		<kanji>ゴルフ</kanji>
		<kana>ゴルフ</kana>
		<english>golf</english>
	</listItem>
	<listItem>
		<kanji>セーター</kanji>
		<kana>セーター</kana>
		<english>sweater</english>
	</listItem>
	<listItem>
		<kanji>象</kanji>
		<kana>ぞう</kana>
		<english>elephant</english>
	</listItem>
	<listItem>
		<kanji>バイオリン</kanji>
		<kana>バイオリン</kana>
		<english>violin</english>
	</listItem>
	<listItem>
		<kanji>バイク</kanji>
		<kana>バイク</kana>
		<english>motorcycle</english>
	</listItem>
	<listItem>
		<kanji>物価</kanji>
		<kana>ぶっか</kana>
		<english>(consumer) prices</english>
	</listItem>
	<listItem>
		<kanji>文法</kanji>
		<kana>ぶんぽう</kana>
		<english>grammar</english>
	</listItem>
	<listItem>
		<kanji>弁護士</kanji>
		<kana>べんごし</kana>
		<english>lawyer</english>
	</listItem>
	<listItem>
		<kanji>募集</kanji>
		<kana>ぼしゅう</kana>
		<english>recruitment</english>
	</listItem>
	<listItem>
		<kanji>店</kanji>
		<kana>みせ</kana>
		<english>shop; store</english>
	</listItem>
	<listItem>
		<kanji>やくざ</kanji>
		<kana>やくざ</kana>
		<english>gangster</english>
	</listItem>
	<listItem>
		<kanji>約束</kanji>
		<kana>やくそく</kana>
		<english>promise; appointment</english>
	</listItem>
	<listItem>
		<kanji>レポート</kanji>
		<kana>レポート</kana>
		<english>(term) paper</english>
	</listItem>
	<listItem>
		<kanji>私</kanji>
		<kana>わたしく</kana>
		<english>I (formal)</english>
	</listItem>
	<listItem>
		<kanji>うれしい</kanji>
		<kana>うれしい</kana>
		<english>glad</english>
	</listItem>
	<listItem>
		<kanji>悲しい</kanji>
		<kana>かなしい</kana>
		<english>sad</english>
	</listItem>
	<listItem>
		<kanji>辛い</kanji>
		<kana>からい</kana>
		<english>hot and spicy; salty</english>
	</listItem>
	<listItem>
		<kanji>厳しい</kanji>
		<kana>きびしい</kana>
		<english>strict</english>
	</listItem>
	<listItem>
		<kanji>すごい</kanji>
		<kana>すごい</kana>
		<english>incredible; awesome</english>
	</listItem>
	<listItem>
		<kanji>近い</kanji>
		<kana>ちかい</kana>
		<english>close; near</english>
	</listItem>
	<listItem>
		<kanji>色々（な）</kanji>
		<kana>いろいら（な）</kana>
		<english>various; different kinds of</english>
	</listItem>
	<listItem>
		<kanji>幸せ（な）</kanji>
		<kana>しあわせ（な）</kana>
		<english>happy (lasting happiness)</english>
	</listItem>
	<listItem>
		<kanji>だめ（な）</kanji>
		<kana>だめ（な）</kana>
		<english>no good</english>
	</listItem>
	<listItem>
		<kanji>（～を）編む</kanji>
		<kana>（～を）あむ</kana>
		<english>to knit</english>
	</listItem>
	<listItem>
		<kanji>（personにthingを）貸す</kanji>
		<kana>（personにthingを）かす</kana>
		<english>to lend; to rent (thing to person)</english>
	</listItem>
	<listItem>
		<kanji>頑張る</kanji>
		<kana>がんばる</kana>
		<english>to do one's best; to try hard</english>
	</listItem>
	<listItem>
		<kanji>泣く</kanji>
		<kana>なく</kana>
		<english>to cry</english>
	</listItem>
	<listItem>
		<kanji>（～を）磨く</kanji>
		<kana>（～を）みがく</kana>
		<english>to brush (teeth); to polish (~)</english>
	</listItem>
	<listItem>
		<kanji>約束を守る</kanji>
		<kana>やくそくをまもる</kana>
		<english>to keep a promise</english>
	</listItem>
	<listItem>
		<kanji>（～に）感動する</kanji>
		<kana>（～に）かんどうする</kana>
		<english>to be moved/touched (by ~)</english>
	</listItem>
	<listItem>
		<kanji>いらっしゃいます</kanji>
		<kana>いらっしゃいます</kana>
		<english>(someone honorable) is present/home</english>
	</listItem>
	<listItem>
		<kanji>＃回</kanji>
		<kana>＃かい</kana>
		<english># times</english>
	</listItem>
	<listItem>
		<kanji>＃キロ</kanji>
		<kana>＃キロ</kana>
		<english># kilometers; # kilograms</english>
	</listItem>
	<listItem>
		<kanji>実は</kanji>
		<kana>じつは</kana>
		<english>as a matter of fact...</english>
	</listItem>
	<listItem>
		<kanji>全部</kanji>
		<kana>ぜんぶ</kana>
		<english>all</english>
	</listItem>
	<listItem>
		<kanji>～と申します</kanji>
		<kana>～ともうします</kana>
		<english>my name is ~</english>
	</listItem>
	<listItem>
		<kanji>一日</kanji>
		<kana>いちにち</kana>
		<english>one day</english>
	</listItem>
	<listItem>
		<kanji>二日</kanji>
		<kana>ふつか</kana>
		<english>two days</english>
	</listItem>
	<listItem>
		<kanji>三日</kanji>
		<kana>みっか</kana>
		<english>three days</english>
	</listItem>
	<listItem>
		<kanji>四日</kanji>
		<kana>よっか</kana>
		<english>four days</english>
	</listItem>
	<listItem>
		<kanji>五日</kanji>
		<kana>いつか</kana>
		<english>five days</english>
	</listItem>
	<listItem>
		<kanji>六日</kanji>
		<kana>むいか</kana>
		<english>six days</english>
	</listItem>
	<listItem>
		<kanji>七日</kanji>
		<kana>なのか</kana>
		<english>seven days</english>
	</listItem>
	<listItem>
		<kanji>八日</kanji>
		<kana>ようか</kana>
		<english>eight days</english>
	</listItem>
	<listItem>
		<kanji>九日</kanji>
		<kana>ここのか</kana>
		<english>nine days</english>
	</listItem>
	<listItem>
		<kanji>十日</kanji>
		<kana>とおか</kana>
		<english>ten days</english>
	</listItem>
</kanjiList>
